config/routes.rb
FeedReader::Application.routes.draw do  # The priority is based upon order of creation:
  resources :feeds

  root :to => 'feeds#index'

end

app/models/feed.rb
require 'rss'
require 'open-uri'
class Feed < ActiveRecord::Base
  attr_accessible :name, :feed_url

  def items  
    RSS::Parser.parse(open(feed_url).read, false).items.sort_by { |item| item.pubDate }
    .reverse!
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController
  def index
    @feeds = Feed.all
  end

  def show
    @feed = Feed.find(params[:id])
  end

  def new
    @feed = Feed.new
  end

  def create
    @feed = Feed.new(params[:feed])
    if @feed.save
      redirect_to @feed, :notice => "Successfully created feed."
    else
      render :action => 'new'
    end
  end

  def edit
    @feed = Feed.find(params[:id])
  end

  def update
    @feed = Feed.find(params[:id])
    if @feed.update_attributes(params[:feed])
      redirect_to @feed, :notice  => "Successfully updated feed."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @feed = Feed.find(params[:id])
    @feed.destroy
    redirect_to feeds_url, :notice => "Successfully destroyed feed."
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/feeds_helper.rb
module FeedsHelper
end

app/views/feeds/_form.html.erb
<%= form_for(@feed) do |f| %>
  <% if @feed.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@feed.errors.count, "error") %> prohibited this feed from being saved:</h2>

      <ul>
      <% @feed.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :feed_url %><br />
    <%= f.text_field :feed_url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/feeds/edit.html.erb
<h1>Editing feed</h1>

<%= render 'form' %>

<%= link_to 'Show', @feed %> |
<%= link_to 'Back', feeds_path %>

app/views/feeds/index.html.erb
<h1>Listing feeds</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Feed url</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @feeds.each do |feed| %>
  <tr>
    <td><%= feed.name %></td>
    <td><%= feed.feed_url %></td>
    <td><%= link_to 'Show', feed %></td>
    <td><%= link_to 'Edit', edit_feed_path(feed) %></td>
    <td><%= link_to 'Destroy', feed, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Feed', new_feed_path %>

app/views/feeds/new.html.erb
<h1>New feed</h1>

<%= render 'form' %>

<%= link_to 'Back', feeds_path %>

app/views/feeds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @feed.name %>
</p>

<p>
  <b>Feed url:</b>
  <%= @feed.feed_url %>
</p>
<h3>Feeds list </h3>
<ul>
  <% @feed.items.each do |item|%>
    <li>
      <%=link_to item.title, item.link, target: "_blank" %>
    </li>
  <% end %>
</ul>

<%= link_to 'Edit', edit_feed_path(@feed) %> |
<%= link_to 'Back', feeds_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Feed Reader</title>
    <%= stylesheet_link_tag "application" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tag %>
    <%= yield(:head) %>
  </head>
  <body>
    <div id="container">
      <%= yield %>
    </div>
  </body>
</html>